### ISSUE TITLE
YouTube's API... expired on me?

### ISSUE THREAD

**Issue by MeoMix** [MeoMix/StreamusChromeExtension#381]
I haven't restarted Streamus in >24 hours. I left Streamus paused which trigger the chrome alarm to restart the player after a few hours because YouTube's buffered data stops being valid after a while.

I tried to play a song this morning and saw the following stack trace:

	 Error in event handler for alarms.onAlarm: TypeError: undefined is not a function
		at Backbone.Model.extend.cueVideoById (chrome-extension://jbnkffmindojffecdhbbmekbmkkfpmjd/js/background/model/youTubePlayer.js:105:33)
		at Backbone.Model.extend.activateSong (chrome-extension://jbnkffmindojffecdhbbmekbmkkfpmjd/js/background/model/player.js:91:47)
		at Backbone.Model.extend.refresh (chrome-extension://jbnkffmindojffecdhbbmekbmkkfpmjd/js/background/model/player.js:192:22)
		at Backbone.Model.extend._onChromeAlarmsAlarm (chrome-extension://jbnkffmindojffecdhbbmekbmkkfpmjd/js/background/model/player.js:315:22)

This is pretty crazy because it's saying undefined is not a function on cueVideoById which is the youTubePlayerWidget. The widget itself exists, but the function disappeared? How is that possible?

**Comment by MeoMix** [comment]
Haven't seen this happen again... will re-open if it persists.
